### ISSUE TITLE
US: login module

### ISSUE THREAD

**Issue by cchay** [cchay/chay-family-footsteps#1]
Allow user to create username & password and login to system.

**Comment by christopherchay** [comment]
Hello, I am here!

**Comment by EmmanuelChay** [comment]
Hello!

**Comment by cchay** [comment]
You will need a "user" class that the login module uses to authenticate the user.  It should have:
- [x] UserName
- [x] Password
- [x] FirstName
- [x] LastName

**Comment by CalebChay** [comment]
I'll start working on it immediately.

**Comment by celestachay** [comment]
Hello!

**Comment by celestachay** [comment]
What are we doing,now?

**Comment by EmmanuelChay** [comment]
@christopherchay there is an error :-1: 


@christopherchay After you made the pull request.I git pulled,and re-tried LoginTest.py but there was still a error:


- [x] Traceback (most recent call last):
File "/home/hacker/_/Chay-Family-Footsteps/Test/Unit/LoginTest.py", line 8, in 
Login.Register()

- [x] File "/home/hacker/_/Chay-Family-Footsteps/Test/Unit/../../Login/Login.py", line 43, in Register
usershell.setUsername(username)
AttributeError: 'User' object has no attribute 'setUsername'

**Comment by EmmanuelChay** [comment]
@christopherchay There is still an error! :-1:

**Comment by EmmanuelChay** [comment]
Excellent! Function test complete!
:100: %

**Comment by celestachay** [comment]
IN  WHEREEEEEEEEEEEEEEEEEEEE!!!!!!!!!!!!??????????
😡

**Comment by celestachay** [comment]
GRRrr........................

**Comment by celestachay** [comment]
😃💫

**Comment by christopherchay** [comment]
I am currently working on trying to see if I can write all the User Login data files to the Data/User directory.

**Comment by christopherchay** [comment]
Login.py Works, now I just need the testers to test it.
