### ISSUE TITLE
US:Login:1#

### ISSUE THREAD

**Issue by EmmanuelChay** [cchay/chay-family-footsteps#29]
@christopherchay After you made the pull request.I  git pulled,and re-tried LoginTest.py but there was still a error:

- [ ] Traceback (most recent call last):
  File "/home/hacker/_/Chay-Family-Footsteps/Test/Unit/LoginTest.py", line 8, in <module>
    Login.Register()

- [ ]   File "/home/hacker/_/Chay-Family-Footsteps/Test/Unit/../../Login/Login.py", line 43, in Register
    usershell.setUsername(username)
AttributeError: 'User' object has no attribute 'setUsername'

**Comment by christopherchay** [comment]
Bruh, fixing it now

**Comment by christopherchay** [comment]
It's fixed!
